version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - VITE_VENDURE_API_URL=http://vendure:3000/shop-api
      - HOST=0.0.0.0
    networks:
      - app-network
    depends_on:
      - vendure

  vendure:
    image: ghcr.io/vendure-ecommerce/vendure:latest
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=vendure
      - DB_USERNAME=vendure
      - DB_PASSWORD=vendure
      - SUPERADMIN_USERNAME=superadmin@vendure.io
      - SUPERADMIN_PASSWORD=superadmin
      - COOKIE_SECRET=your-cookie-secret
      - JWT_SECRET=your-jwt-secret
    networks:
      - app-network
    depends_on:
      - postgres

  postgres:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=vendure
      - POSTGRES_USER=vendure
      - POSTGRES_PASSWORD=vendure
    networks:
      - app-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local