version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - VITE_VENDURE_API_URL=http://localhost:3000/shop-api
      - HOST=0.0.0.0
    networks:
      - vendure-network

networks:
  vendure-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16