// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ajvsdhrbvxteusptzfkr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFqdnNkaHJidnh0ZXVzcHR6ZmtyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzczMDMxODUsImV4cCI6MjA1Mjg3OTE4NX0.ieWar97x82Loumt5NRWl3-016wW6zmT3AJCQDOIuUSc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);